spring.application.name=dine-in-order-api

#DATASOURCE CONFIGURATION
spring.datasource.url=jdbc:mysql://localhost:3306/springboot_actordb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Priyanka@20
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

